Update N1-OpenWrt.yml

diff --git a/.github/workflows/N1-OpenWrt.yml b/.github/workflows/N1-OpenWrt.yml
--- a/.github/workflows/N1-OpenWrt.yml
+++ b/.github/workflows/N1-OpenWrt.yml
@@ -111,13 +111,13 @@ jobs:
        
     - name: Copy output images
       run: |
-        IMAGE=$(find ./output -name '*.img.gz' | head -n 1)
-        #IMAGE=$(find ./bin/targets -name '*.img.gz' | head -n 1)
-        if [ -z "$IMAGE" ]; then
-        echo "Image file not found!"
-        exit 1
-        fi
-        cp "$IMAGE" .
+          IMAGE=$(find ./bin/targets -name '*.img.gz' | head -n 1)
+          if [ -z "$IMAGE" ]; then
+          echo "Image file not found!"
+          exit 1
+          fi
+          cp "$IMAGE" .
+          cp "$IMAGE" .
     
     - name: Organize files
       run: |
